name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Permite ejecutar manualmente el workflow
  workflow_dispatch:

# Permisos necesarios para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evita ejecuciones concurrentes
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job para construir el proyecto Java y generar documentación
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn clean compile test
      
    - name: Generate Javadoc
      run: mvn javadoc:javadoc -Dmaven.javadoc.failOnError=false
      
    - name: Copy static files to docs
      run: |
        cp home.html docs/
        cp api-demo.html docs/
        cp demo.html docs/
        cp README.md docs/ || echo "README.md not found"
      
    - name: Copy Javadoc to docs
      run: cp -r target/site/apidocs/* docs/ || echo "Javadoc not generated, continuing..."
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: docs/

  # Job para desplegar a GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: docs/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload to Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
